import rows from "./placePhotos.data.json";

// Photos for the places, all from Wikimedia Commons, downloaded once and served from /photos/.
// placePhotos.data.json is generated by `pnpm photos:fetch` from the curation in
// data/place-photos.json; edit the curation and run the script again rather than editing it.
//
// A place gets its own photo when a verified one exists. Otherwise it gets a photo of its city,
// and failing that a general photo of its type (a restaurant, a market). Those two are never
// presented as the place: their alt text and note say so.

export type PhotoKind = "place" | "city" | "topic";

export interface PlacePhoto {
  kind: PhotoKind; // "place": the place itself; "city" and "topic": a stand-in
  src: string; // the 960 px file
  srcSet: string; // the 500 px and 960 px files, for <img srcSet>
  width: number; // of the 960 px file, for the aspect ratio
  height: number;
  alt: string;
  credit: string; // "Photo: <author>, <license>", shown with the photo
  author: string;
  license: string;
  licenseUrl: string | null; // null for public domain
  sourceUrl: string; // the file's page on Wikimedia Commons
  focal: string; // CSS object-position that keeps the subject in a square crop
  note: string | null; // null for the place's own photo, else says what the photo is not
}

/** One row of placePhotos.data.json (written by scripts/fetch-place-photos.ts). */
interface PhotoRow {
  key: string; // a place id, "city:<City>" or "type:<type>"
  file: string;
  sourceUrl: string;
  author: string;
  license: string;
  licenseUrl: string | null;
  width: number;
  height: number;
  description: string;
  focal: string;
}

const ROWS: readonly PhotoRow[] = rows;

const byPlace = new Map<string, PhotoRow>();
const byCity = new Map<string, PhotoRow>();
const byType = new Map<string, PhotoRow>();
for (const row of ROWS) {
  if (row.key.startsWith("city:")) byCity.set(row.key.slice("city:".length), row);
  else if (row.key.startsWith("type:")) byType.set(row.key.slice("type:".length), row);
  else byPlace.set(row.key, row);
}

/**
 * Six of the best own photos, one or two per base (Rome, Florence, Venice, Milan, Bologna),
 * in the order a strip of highlights shows them.
 */
export const HIGHLIGHT_PLACE_IDS: readonly string[] = [
  "place_001", // Colosseum, Rome
  "place_084", // Ponte Vecchio, Florence
  "place_066", // Rialto Bridge, Venice
  "place_055", // Duomo di Milano
  "place_048", // Torre degli Asinelli, Bologna
  "place_018", // Trevi Fountain, Rome
];

/** The file name stem of a key, as the fetch script writes it: "city:Rome" is "city-rome". */
function fileStem(key: string): string {
  return key.toLowerCase().replace(":", "-").replaceAll(" ", "-");
}

function toPhoto(row: PhotoRow, kind: PhotoKind, alt: string, note: string | null): PlacePhoto {
  const stem = `/photos/${fileStem(row.key)}`;
  return {
    kind,
    src: `${stem}-960.jpg`,
    srcSet: `${stem}-500.jpg 500w, ${stem}-960.jpg 960w`,
    width: row.width,
    height: row.height,
    alt,
    credit: `Photo: ${row.author}, ${row.license}`,
    author: row.author,
    license: row.license,
    licenseUrl: row.licenseUrl,
    sourceUrl: row.sourceUrl,
    focal: row.focal,
    note,
  };
}

/** The place's own photo, else a photo of its city, else a general photo of its type, else null. */
export function photoForPlace(place: {
  id: string;
  name: string;
  city: string;
  type: string;
}): PlacePhoto | null {
  const own = byPlace.get(place.id);
  if (own) return toPhoto(own, "place", own.description, null);
  const city = byCity.get(place.city);
  if (city) {
    const alt = `${city.description} (a photo of ${place.city}, not ${place.name})`;
    return toPhoto(city, "city", alt, `City photo of ${place.city}, not this place.`);
  }
  const topic = byType.get(place.type);
  if (topic) {
    const alt = `${topic.description} (a general photo, not ${place.name})`;
    return toPhoto(topic, "topic", alt, "General photo, not this place.");
  }
  return null;
}

/** True when the place has a verified photo of itself, not a city or general one. */
export function placeHasOwnPhoto(placeId: string): boolean {
  return byPlace.has(placeId);
}

/** One photo's credit, for the list in "About this data". */
export interface PhotoCreditRow {
  key: string; // a place id, "city:<City>" or "type:<type>"
  kind: PhotoKind;
  subject: string; // the place id, the city or the type
  author: string;
  license: string;
  licenseUrl: string | null;
  sourceUrl: string;
  title: string; // the Commons file's name: "Bologna, Strada Maggiore, Piazetta dei Servi"
}

/** Every photo the site serves, with its credit, in the order of the data file (by key). */
export function photoCredits(rows: readonly PhotoRow[] = ROWS): PhotoCreditRow[] {
  return rows.map((row) => {
    const [prefix, rest] = row.key.includes(":") ? row.key.split(":", 2) : [null, row.key];
    const kind: PhotoKind = prefix === "city" ? "city" : prefix === "type" ? "topic" : "place";
    return {
      key: row.key,
      kind,
      subject: rest ?? row.key,
      author: row.author,
      license: row.license,
      licenseUrl: row.licenseUrl,
      sourceUrl: row.sourceUrl,
      title: row.file.replace(/^File:/, "").replace(/\.[a-z0-9]+$/i, ""),
    };
  });
}
